- app/config/FrontendAppConfig.scala
- app/controllers/register/establishers/company/AddCompanyDirectorsController.scala
- app/controllers/register/establishers/company/director/ConfirmDeleteDirectorController.scala
- app/forms/register/establishers/company/AddCompanyDirectorsFormProvider.scala
- app/identifiers/register/establishers/company/AddCompanyDirectorsId.scala
- app/identifiers/register/establishers/company/director/DirectorDetailsId.scala
- app/models/register/establishers/company/director/DirectorDetails.scala
- app/utils/CheckYourAnswersHelper.scala
- app/utils/UserAnswers.scala
- app/viewmodels/Person.scala
- app/views/components/paragraph_text.scala.html
- app/views/components/person_list.scala.html
- app/views/register/establishers/company/addCompanyDirectors.scala.html
- conf/application.conf
- conf/establishers.routes
- conf/messages.en
- migrations/applied_migrations
- test/connectors/FakeDataCacheConnector.scala
- test/controllers/register/establishers/company/AddCompanyDirectorsControllerSpec.scala
- test/forms/register/establishers/company/AddCompanyDirectorsFormProviderSpec.scala
- test/views/behaviours/PeopleListBehaviours.scala
- test/views/behaviours/YesNoViewBehaviours.scala
- test/views/register/establishers/AddEstablisherViewSpec.scala
- test/views/register/establishers/company/AddCompanyDirectorsViewSpec.scala
View and spec
Controller and spec
Tidy up
Fixes after rebase
> PODS-231: Add company directors

- app/connectors/DataCacheConnector.scala
- app/connectors/MicroserviceCacheConnector.scala
- app/connectors/MongoCacheConnector.scala
- app/controllers/register/establishers/company/director/ConfirmDeleteDirectorController.scala
- app/identifiers/register/establishers/company/director/ConfirmDeleteDirectorId.scala
- app/views/register/establishers/company/director/confirmDeleteDirector.scala.html
- conf/establishers.routes
- conf/messages.en
- migrations/applied_migrations
- test/connectors/FakeDataCacheConnector.scala
- test/connectors/MicroserviceCacheConnectorSpec.scala
- test/controllers/register/establishers/company/director/ConfirmDeleteDirectorControllerSpec.scala
- test/views/register/establishers/company/director/ConfirmDeleteDirectorViewSpec.scala
View and controller tests
Add remove to DataCacheConnector
Controller and spec
> PODS-547: Confirm delete director

- app/controllers/register/SchemeReviewController.scala
- app/identifiers/register/SchemeReviewId.scala
- app/views/components/review_section.scala.html
- app/views/register/establishers/company/companyReview.scala.html
- app/views/register/schemeReview.scala.html
- conf/messages.en
- conf/register.routes
- migrations/applied_migrations
- test/controllers/register/SchemeReviewControllerSpec.scala
- test/views/register/SchemeReviewViewSpec.scala
refactored companyReview page as well to use new component review_section
> Pods 282 Reg scheme - scheme info - create screen for review

- app/controllers/register/trustees/individual/TrusteeAddressYearsController.scala
- app/identifiers/register/trustees/individual/TrusteeAddressYearsId.scala
- app/utils/CheckYourAnswersHelper.scala
- conf/messages.en
- conf/trustees.routes
- test/controllers/register/trustees/individual/TrusteeAddressYearsControllerSpec.scala
> PODS-277: Trustee individual address years

- app/controllers/register/trustees/individual/TrusteeContactDetailsController.scala
- app/identifiers/register/trustees/individual/TrusteeContactDetailsId.scala
- app/utils/CheckYourAnswersHelper.scala
- app/views/register/trustees/individual/trusteeContactDetails.scala.html
- conf/messages.en
- conf/trustees.routes
- migrations/applied_migrations
- test/controllers/register/trustees/individual/TrusteeContactDetailsControllerSpec.scala
- test/views/register/trustees/individual/TrusteeContactDetailsViewSpec.scala
Model and form
View
Controller
Tidy up
> PODS-169: Trustee individual contact details

- app/controllers/register/trustees/ConfirmDeleteTrusteeController.scala
- app/identifiers/register/trustees/ConfirmDeleteTrusteeId.scala
- app/identifiers/register/trustees/TrusteeKindId.scala
- app/identifiers/register/trustees/TrusteesId.scala
- app/identifiers/register/trustees/company/CompanyAddressId.scala
- app/identifiers/register/trustees/company/CompanyAddressYearsId.scala
- app/identifiers/register/trustees/company/CompanyContactDetailsId.scala
- app/identifiers/register/trustees/company/CompanyDetailsId.scala
- app/identifiers/register/trustees/company/CompanyPreviousAddressId.scala
- app/identifiers/register/trustees/company/CompanyRegistrationNumberId.scala
- app/identifiers/register/trustees/individual/TrusteeAddressId.scala
- app/identifiers/register/trustees/individual/TrusteeAddressYearsId.scala
- app/identifiers/register/trustees/individual/TrusteeDetailsId.scala
- app/identifiers/register/trustees/individual/TrusteeNinoId.scala
- app/identifiers/register/trustees/individual/TrusteePreviousAddressId.scala
- app/identifiers/register/trustees/individual/TrusteePreviousAddressListId.scala
- app/identifiers/register/trustees/individual/UniqueTaxReferenceId.scala
- app/models/register/trustees/TrusteeKind.scala
- app/utils/UserAnswers.scala
- app/views/register/trustees/confirmDeleteTrustee.scala.html
- conf/messages.en
- conf/trustees.routes
- migrations/applied_migrations
- project/MicroService.scala
- test/controllers/register/trustees/ConfirmDeleteTrusteeControllerSpec.scala
- test/views/ViewSpecBase.scala
- test/views/behaviours/PeopleListBehaviours.scala
- test/views/register/trustees/ConfirmDeleteTrusteeViewSpec.scala
View
Controller
Refactored Id's to delete array not details
Tidy up
> PODS-551: Confirm delete trustee

- app/config/FrontendAppConfig.scala
- app/controllers/register/establishers/EstablisherKindController.scala
- app/views/register/establishers/establisherKind.scala.html
- app/views/register/trustees/trusteeKind.scala.html
- conf/application.conf
- test/views/register/establishers/EstablisherKindViewSpec.scala
- test/views/register/trustees/TrusteeKindViewSpec.scala
> PODS-752: Toggle partnerships

- app/forms/register/AdviserDetailsFormProvider.scala
- app/models/register/AdviserDetails.scala
- app/utils/CheckYourAnswersHelper.scala
- app/views/register/adviser/adviserDetails.scala.html
- conf/messages.en
- test/controllers/ControllerSpecBase.scala
- test/controllers/register/adviser/AdviserDetailsControllerSpec.scala
- test/controllers/register/adviser/CheckYourAnswersControllerSpec.scala
- test/forms/register/AdviserDetailsFormProviderSpec.scala
- test/identifiers/register/DeclarationDutiesIdSpec.scala
- test/views/register/adviser/AdviserDetailsViewSpec.scala
Reverts hmrc/pensions-scheme-frontend#204
> Revert "PODS-867 added phone field in adviser details"

- app/audit/AddressEvent.scala
- app/controllers/address/ManualAddressController.scala
- app/controllers/register/InsurerAddressController.scala
- app/controllers/register/adviser/AdviserAddressController.scala
- app/controllers/register/establishers/company/CompanyAddressController.scala
- app/controllers/register/establishers/company/CompanyPreviousAddressController.scala
- app/controllers/register/establishers/company/director/DirectorAddressController.scala
- app/controllers/register/establishers/company/director/DirectorPreviousAddressController.scala
- app/controllers/register/establishers/individual/AddressController.scala
- app/controllers/register/establishers/individual/PreviousAddressController.scala
- app/controllers/register/trustees/company/CompanyAddressController.scala
- app/controllers/register/trustees/company/CompanyPreviousAddressController.scala
- app/controllers/register/trustees/individual/TrusteeAddressController.scala
- app/controllers/register/trustees/individual/TrusteePreviousAddressController.scala
- test/audit/AddressEventSpec.scala
- test/controllers/address/ManualAddressControllerSpec.scala
- test/controllers/register/InsurerAddressControllerSpec.scala
- test/controllers/register/adviser/AdviserAddressControllerSpec.scala
- test/controllers/register/establishers/company/CompanyAddressControllerSpec.scala
- test/controllers/register/establishers/company/CompanyPreviousAddressControllerSpec.scala
- test/controllers/register/establishers/company/director/DirectorAddressControllerSpec.scala
- test/controllers/register/establishers/company/director/DirectorPreviousAddressControllerSpec.scala
- test/controllers/register/establishers/individual/AddressControllerSpec.scala
- test/controllers/register/establishers/individual/PreviousAddressControllerSpec.scala
- test/controllers/register/trustees/company/CompanyAddressControllerSpec.scala
- test/controllers/register/trustees/company/CompanyPreviousAddressControllerSpec.scala
- test/controllers/register/trustees/individual/TrusteeAddressControllerSpec.scala
- test/controllers/register/trustees/individual/TrusteePreviousAddressControllerSpec.scala
> PODS-1094: Update Plunk Event for Addresses

- app/controllers/register/establishers/company/CompanyPreviousAddressController.scala
- app/controllers/register/establishers/individual/PreviousAddressListController.scala
- test/controllers/register/establishers/company/CompanyPreviousAddressControllerSpec.scala
- test/controllers/register/establishers/individual/PreviousAddressListControllerSpec.scala
Individual previous address list
> PODS-1102: Fix journey test fails

- app/identifiers/LastPageId.scala
- app/models/LastPage.scala
- app/models/requests/DataRequest.scala
- app/utils/Navigator2.scala
- test/connectors/FakeDataCacheConnector.scala
- test/utils/FakeNavigator2.scala
- test/utils/Navigator2Spec.scala
- test/utils/NavigatorBehaviour2.scala
> PODS-1157: Save last page navigator

- app/PODSModule.scala
- app/controllers/register/establishers/company/AddCompanyDirectorsController.scala
- app/controllers/register/establishers/company/CheckYourAnswersController.scala
- app/controllers/register/establishers/company/CompanyContactDetailsController.scala
- app/controllers/register/establishers/company/CompanyDetailsController.scala
- app/controllers/register/establishers/company/CompanyRegistrationNumberController.scala
- app/controllers/register/establishers/company/CompanyReviewController.scala
- app/controllers/register/establishers/company/CompanyUniqueTaxReferenceController.scala
- app/controllers/register/establishers/company/OtherDirectorsController.scala
- app/identifiers/register/establishers/company/CheckYourAnswersId.scala
- app/navigators/EstablishersCompanyNavigator2.scala
- conf/application.conf
- test/controllers/register/establishers/company/AddCompanyDirectorsControllerSpec.scala
- test/controllers/register/establishers/company/CheckYourAnswersControllerSpec.scala
- test/controllers/register/establishers/company/CompanyContactDetailsControllerSpec.scala
- test/controllers/register/establishers/company/CompanyDetailsControllerSpec.scala
- test/controllers/register/establishers/company/CompanyRegistrationNumberControllerSpec.scala
- test/controllers/register/establishers/company/CompanyReviewControllerSpec.scala
- test/controllers/register/establishers/company/CompanyUniqueTaxReferenceControllerSpec.scala
- test/controllers/register/establishers/company/OtherDirectorsControllerSpec.scala
- test/navigators/EstablishersCompanyNavigator2Spec.scala
- test/utils/FakeNavigator2.scala
CompanyDetailsController
CompanyRegistrationNumberController
CompanyUniqueTaxReferenceController
CompanyContactDetailsController
AddCompanyDirectorsController
OtherDirectorsController
CompanyReviewController
CheckYourAnswersController
CheckYourAnswers navigation
> PODS-1179: Add save last page to Establishers Company Navigator

- app/PODSModule.scala
- app/controllers/register/establishers/AddEstablisherController.scala
- app/controllers/register/establishers/ConfirmDeleteEstablisherController.scala
- app/controllers/register/establishers/EstablisherKindController.scala
- app/navigators/EstablishersCompanyNavigator2.scala
- app/navigators/EstablishersNavigator2.scala
- test/controllers/register/establishers/AddEstablisherControllerSpec.scala
- test/controllers/register/establishers/ConfirmDeleteEstablisherControllerSpec.scala
- test/controllers/register/establishers/EstablisherKindControllerSpec.scala
- test/navigators/EstablishersNavigator2Spec.scala
- test/navigators/NavigatorBehaviour2.scala
AddEstablisherController
EstablisherKindController
ConfirmDeleteEstablisherController
Fixes after rebase - feature toggle removal
> PODS-1181: Add save last page to Establishers Navigator

- app/PODSModule.scala
- app/controllers/register/trustees/AddTrusteeController.scala
- app/controllers/register/trustees/ConfirmDeleteTrusteeController.scala
- app/controllers/register/trustees/HaveAnyTrusteesController.scala
- app/controllers/register/trustees/MoreThanTenTrusteesController.scala
- app/controllers/register/trustees/TrusteeKindController.scala
- app/navigators/TrusteesNavigator2.scala
- test/controllers/register/trustees/AddTrusteeControllerSpec.scala
- test/controllers/register/trustees/ConfirmDeleteTrusteeControllerSpec.scala
- test/controllers/register/trustees/HaveAnyTrusteesControllerSpec.scala
- test/controllers/register/trustees/MoreThanTenTrusteesControllerSpec.scala
- test/controllers/register/trustees/TrusteeKindControllerSpec.scala
- test/navigators/TrusteesNavigator2Spec.scala
HaveAnyTrusteesController
AddTrusteeController
MoreThanTenTrusteesController
TrusteeKindController
ConfirmDeleteTrusteeController
> PODS-1185: Add save last page to Trustees Navigator

- app/utils/CheckYourAnswersHelper.scala
- app/utils/checkyouranswers/CheckYourAnswers.scala
- app/viewmodels/AnswerRow.scala
- test/controllers/register/CheckYourAnswersControllerSpec.scala
- test/controllers/register/adviser/CheckYourAnswersControllerSpec.scala
- test/controllers/register/establishers/company/CheckYourAnswersControllerSpec.scala
- test/controllers/register/establishers/company/director/CheckYourAnswersControllerSpec.scala
- test/controllers/register/establishers/individual/CheckYourAnswersControllerSpec.scala
- test/controllers/register/trustees/individual/CheckYourAnswersControllerSpec.scala
- test/utils/CheckYourAnswerHelperSpec.scala
- test/utils/CheckYourAnswersSpec.scala
- test/views/behaviours/CheckYourAnswersBehaviours.scala
PODS-1756 : initial changes to make the answer row with optional change url
> PODS-1756 : initial changes to make the answer row with optional change url

- app/config/FrontendAppConfig.scala
- app/controllers/PSASchemeDetailsController.scala
- app/models/details/transformation/IndividualInfoRows.scala
- app/views/psa_scheme_details.scala.html
- conf/application.conf
- conf/messages.en
- test/controllers/PSASchemeDetailsControllerSpec.scala
- test/models/details/transformation/IndividualInfoRowsSpec.scala
- test/views/PsaSchemeDetailsViewSpec.scala
PODS-1776 : update the director details and partner details layout  and return link
> PODS-1776 : update the director details and partner details layout  and return link

- app/controllers/PSASchemeDetailsController.scala
- test/controllers/PSASchemeDetailsControllerSpec.scala
> PODS-1817 Restrict user to viewing schemes for which they are an administrator

- app/controllers/WorkingKnowledgeController.scala
- app/forms/WorkingKnowledgeFormProvider.scala
- app/views/workingKnowledge.scala.html
- conf/app.routes
- conf/messages.en
- test/controllers/WorkingKnowledgeControllerSpec.scala
- test/forms/WorkingKnowledgeFormProviderSpec.scala
- test/views/WorkingKnowledgeViewSpec.scala
PODS-1996 : Create "Working Knowledge" page
> PODS-1996 : Create "Working Knowledge" page

- app/controllers/register/DeclarationController.scala
- app/navigators/RegisterNavigator.scala
- test/controllers/register/DeclarationControllerSpec.scala
- test/navigators/RegisterNavigatorSpec.scala
PODS-2018 : update the submission logic for declaration
> PODS-2018 : update the submission logic for declaration

- app/controllers/CheckYourAnswersBankDetailsController.scala
- app/controllers/WhatYouWillNeedBankDetailsController.scala
- app/controllers/WhatYouWillNeedController.scala
- app/navigators/AboutBankDetailsNavigator.scala
- test/controllers/CheckYourAnswersBankDetailsControllerSpec.scala
- test/controllers/WhatYouWillNeedBankDetailsControllerSpec.scala
- test/navigators/AboutBankDetailsNavigatorSpec.scala
PODS-1928 : H&S sch reg - About - Bank - NAVIGATION
> PODS-1928 : H&S sch reg - About - Bank - NAVIGATION

- app/controllers/register/trustees/ConfirmDeleteTrusteeController.scala
- app/forms/register/trustees/ConfirmDeleteTrusteeFormProvider.scala
- app/views/register/trustees/confirmDeleteTrustee.scala.html
- test/controllers/register/trustees/ConfirmDeleteTrusteeControllerSpec.scala
- test/forms/register/trustees/ConfirmDeleteTrusteeFormProviderSpec.scala
- test/views/register/trustees/ConfirmDeleteTrusteeViewSpec.scala
PODS-2123 : Add radio buttons for 'Are you sure you want to delete the trustee?'
> PODS-2123 : Add radio buttons for 'Are you sure you want to delete the trustee?'

- app/controllers/register/establishers/partnership/partner/ConfirmDeletePartnerController.scala
- app/controllers/register/trustees/ConfirmDeleteTrusteeController.scala
- app/forms/register/establishers/partnership/partner/ConfirmDeletePartnerFormProvider.scala
- app/views/register/establishers/partnership/partner/confirmDeletePartner.scala.html
- test/controllers/register/establishers/partnership/partner/ConfirmDeletePartnerControllerSpec.scala
- test/forms/register/establishers/partnership/partner/ConfirmDeletePartnerFormProviderSpec.scala
- test/views/register/establishers/partnership/partner/ConfirmDeletePartnerViewSpec.scala
PODS-2124 : Add radio buttons for 'Are you sure you want to delete [partner name]?
> PODS-2124 : Add radio buttons for 'Are you sure you want to delete [partner name]?

- app/controllers/register/establishers/company/director/ConfirmDeleteDirectorController.scala
- app/controllers/register/establishers/company/director/DirectorUniqueTaxReferenceController.scala
- app/forms/register/establishers/company/director/ConfirmDeleteDirectorFormProvider.scala
- app/views/register/establishers/company/director/confirmDeleteDirector.scala.html
- conf/messages.en
- test/controllers/register/establishers/company/director/ConfirmDeleteDirectorControllerSpec.scala
- test/forms/register/establishers/company/director/ConfirmDeleteDirectorFormProviderSpec.scala
- test/views/register/establishers/company/director/ConfirmDeleteDirectorViewSpec.scala
PODS-2050 : Add Yes/No Radion buttons to Confirm Delete Director page and replace cancel link with redirect link
> PODS-2050 : Add Yes/No Radion buttons to Confirm Delete Director page and replace cancel link with redirect link	

- app/controllers/register/establishers/ConfirmDeleteEstablisherController.scala
- app/controllers/register/trustees/ConfirmDeleteTrusteeController.scala
- app/forms/register/establishers/ConfirmDeleteEstablisherFormProvider.scala
- app/identifiers/register/establishers/ConfirmDeleteEstablisherId.scala
- app/identifiers/register/trustees/ConfirmDeleteTrusteeId.scala
- app/views/register/establishers/confirmDeleteEstablisher.scala.html
- test/controllers/register/establishers/ConfirmDeleteEstablisherControllerSpec.scala
- test/forms/register/establishers/ConfirmDeleteEstablisherFormProviderSpec.scala
- test/views/register/establishers/ConfirmDeleteEstablisherViewSpec.scala
PODS-2128 : Add radio buttons for 'Are you sure you want to delete [establisher name]?'
> PODS-2128 : Add radio buttons for 'Are you sure you want to delete [establisher name]?'

- conf/messages.en
PODS-2241: BUG - tab title to be made consistent for scheme frontend
> PODS-2241: BUG - tab title to be made consistent for scheme frontend

- app/views/check_your_answers.scala.html
- conf/messages.en
- test/views/CheckYourAnswersViewSpec.scala
fix to use the correct title and h1
> fix to use the correct title and h1

- app/config/FrontendAppConfig.scala
- app/connectors/PensionsSchemeConnector.scala
- conf/application.conf
- test/connectors/PensionsSchemeConnectorSpec.scala
- test/controllers/register/DeclarationControllerSpec.scala
PODS-2287: Scheme variances - front end connector
> PODS-2287: Scheme variances - front end connector

- app/models/register/Entity.scala
- app/utils/HsTaskListHelper.scala
- app/utils/UserAnswers.scala
- app/views/components/entity_list.scala.html
- conf/messages.en
- test/controllers/register/establishers/AddEstablisherControllerSpec.scala
- test/controllers/register/establishers/company/AddCompanyDirectorsControllerSpec.scala
- test/controllers/register/establishers/partnership/AddPartnersControllerSpec.scala
- test/controllers/register/trustees/AddTrusteeControllerSpec.scala
- test/models/register/EntitySpec.scala
- test/utils/UserAnswersSpec.scala
- test/views/behaviours/EntityListBehaviours.scala
- test/views/register/AddPartnersViewSpec.scala
- test/views/register/establishers/AddEstablisherViewSpec.scala
- test/views/register/establishers/company/AddCompanyDirectorsViewSpec.scala
- test/views/register/trustees/AddTrusteeViewSpec.scala
changed to make entity edit and delete links optional
> changed to make entity edit and delete links optional

- app/controllers/AnyMoreChangesController.scala
- app/forms/AnyMoreChangesFormProvider.scala
- app/identifiers/AnyMoreChangesId.scala
- app/navigators/AboutBenefitsAndInsuranceNavigator.scala
- app/navigators/EstablishersCompanyNavigator.scala
- app/navigators/EstablishersIndividualNavigator.scala
- app/navigators/EstablishersPartnershipNavigator.scala
- app/navigators/VariationsNavigator.scala
- app/views/anyMoreChanges.scala.html
- conf/app.routes
- conf/prod.routes
- conf/vary.routes
- test/controllers/AnyMoreChangesControllerSpec.scala
- test/navigators/AboutBenefitsAndInsuranceNavigatorSpec.scala
- test/navigators/EstablishersCompanyNavigatorSpec.scala
- test/navigators/EstablishersIndividualNavigatorSpec.scala
- test/navigators/EstablishersPartnershipNavigatorSpec.scala
- test/navigators/VariationsNavigatorSpec.scala
- test/views/AnyMoreChangesViewSpec.scala
> vary package removed

- app/utils/UserAnswers.scala
- test/utils/UserAnswersSpec.scala
refactoring and fixing the remove link conditions
> refactoring and fixing the remove link conditions

- conf/application.conf
PODS-2673: feedback servey link updated
> PODS-2673: feedback servey link updated

- conf/app.routes
PODS-2670: Scheme Reg - Benefits Insurance - Extra '/' in "enter the address manually" link
> PODS-2670: Scheme Reg - Benefits Insurance - Extra '/' in "enter the address manually" link

- app/controllers/InsurancePolicyNumberController.scala
- app/identifiers/InsurancePolicyNumberId.scala
- app/views/insurancePolicyNumber.scala.html
- conf/application.conf
- conf/messages.en
- test/controllers/InsurancePolicyNumberControllerSpec.scala
- test/views/InsurancePolicyNumberViewSpec.scala
PODS-2616 : Scheme Variances | check-your-answers-benefits-insurance add link going to Service Reset
> PODS-2616 : Scheme Variances | check-your-answers-benefits-insurance add link going to Service Reset

- app/controllers/register/trustees/company/CompanyDetailsController.scala
- app/controllers/register/trustees/individual/TrusteeDetailsController.scala
- app/controllers/register/trustees/partnership/TrusteeDetailsController.scala
- app/models/register/Entity.scala
- app/navigators/EstablishersCompanyDirectorNavigator.scala
- app/navigators/EstablishersCompanyNavigator.scala
- app/navigators/EstablishersIndividualNavigator.scala
- app/navigators/EstablishersPartnerNavigator.scala
- app/navigators/EstablishersPartnershipNavigator.scala
- app/navigators/TrusteesCompanyNavigator.scala
- app/navigators/TrusteesIndividualNavigator.scala
- app/navigators/TrusteesPartnershipNavigator.scala
- app/utils/hstasklisthelper/HsTaskListHelper.scala
- app/utils/hstasklisthelper/HsTaskListHelperRegistration.scala
- app/utils/hstasklisthelper/HsTaskListHelperVariations.scala
- conf/application.conf
- test/models/register/EntitySpec.scala
- test/navigators/EstablishersCompanyDirectorNavigatorSpec.scala
- test/navigators/EstablishersCompanyNavigatorSpec.scala
- test/navigators/EstablishersIndividualNavigatorSpec.scala
- test/navigators/EstablishersPartnerNavigatorSpec.scala
- test/navigators/EstablishersPartnershipNavigatorSpec.scala
- test/utils/HsTaskListHelperRegistrationSpec.scala
- test/utils/HsTaskListHelperVariationsSpec.scala
PODS-2672 : Navigation for new establisher from cya page is not working correctly
> PODS-2672 : Navigation for new establisher from cya page is not working correctly

- app/controllers/AnyMoreChangesController.scala
- app/controllers/CheckYourAnswersBenefitsAndInsuranceController.scala
- app/controllers/CheckYourAnswersMembersController.scala
- app/controllers/VariationDeclarationController.scala
- app/controllers/register/establishers/company/CheckYourAnswersController.scala
- app/controllers/register/establishers/company/director/CheckYourAnswersController.scala
- app/controllers/register/establishers/individual/CheckYourAnswersController.scala
- app/controllers/register/establishers/partnership/CheckYourAnswersController.scala
- app/controllers/register/establishers/partnership/partner/CheckYourAnswersController.scala
- app/controllers/register/trustees/company/CheckYourAnswersController.scala
- app/controllers/register/trustees/individual/CheckYourAnswersController.scala
- app/controllers/register/trustees/partnership/CheckYourAnswersController.scala
- app/views/anyMoreChanges.scala.html
- app/views/register/establishers/addEstablisher.scala.html
- app/views/register/establishers/company/companyReview.scala.html
- app/views/register/establishers/partnership/partnershipReview.scala.html
- app/views/register/trustees/addTrustee.scala.html
- app/views/variationDeclaration.scala.html
- test/controllers/AnyMoreChangesControllerSpec.scala
- test/controllers/VariationDeclarationControllerSpec.scala
- test/views/AnyMoreChangesViewSpec.scala
- test/views/VariationDeclarationViewSpec.scala
- test/views/ViewSpecBase.scala
- test/views/behaviours/ViewBehaviours.scala
- test/views/register/establishers/AddEstablisherViewSpec.scala
- test/views/register/establishers/company/CompanyReviewViewSpec.scala
- test/views/register/establishers/partnership/PartnershipReviewViewSpec.scala
- test/views/register/trustees/AddTrusteeViewSpec.scala
PODS-2388 : Sch variances - Add return link - Update return links on changes pages to take user back to the scheme details page
> PODS-2388 : Sch variances - Add return link - Update return links on changes pages to take user back to the scheme details page

- app/navigators/AboutBenefitsAndInsuranceNavigator.scala
- test/navigators/AboutBenefitsAndInsuranceNavigatorSpec.scala
PODS-2491 : insurance and benefit navigation for subscription
> PODS-2491 : insurance and benefit navigation for subscription

- app/utils/hstasklisthelper/HsTaskListHelper.scala
- app/views/register/establishers/company/companyReview.scala.html
- app/views/register/establishers/partnership/partnershipReview.scala.html
- conf/messages.en
- test/utils/behaviours/HsTaskListHelperBehaviour.scala
- test/views/register/establishers/company/CompanyReviewViewSpec.scala
- test/views/register/establishers/partnership/PartnershipReviewViewSpec.scala
PODS-2686 : Scheme Variations - When only 1 Director or Partner, link on Review page shows Add, delete or edit
> PODS-2686 : Scheme Variations - When only 1 Director or Partner, link on Review page shows Add, delete or edit

- app/assets/stylesheets/partials/_scheme__list.scss
- app/assets/stylesheets/pensionsschemefrontend-app.scss
- conf/messages.en
> Pods 2662 changes in lozenge/tag status

- app/utils/Toggles.scala
- conf/application.conf
- test/toggles/TogglesSpec.scala
PODS-2807: toggle added for Hub and spoke for establishers company
> PODS-2807: toggle added for Hub and spoke for establishers company

- app/identifiers/register/establishers/company/CompanyEmailId.scala
- app/identifiers/register/establishers/company/CompanyPhoneId.scala
- app/identifiers/register/establishers/company/CompanyTradingTimeId.scala
- app/identifiers/register/establishers/company/HasCompanyNumberId.scala
- app/identifiers/register/establishers/company/HasCompanyPAYEId.scala
- app/identifiers/register/establishers/company/HasCompanyUTRId.scala
- app/identifiers/register/establishers/company/HasCompanyVATId.scala
- app/identifiers/register/establishers/company/NoCompanyNumberId.scala
- app/identifiers/register/establishers/company/NoCompanyUTRId.scala
PODS-2826: Add ids for new pages
> PODS-2826: Add ids for new pages

- conf/application.conf
- test/toggles/TogglesSpec.scala
PODS-2805: Toggle on pensions-scheme data shift
> PODS-2805: Toggle on pensions-scheme data shift

- app/views/schemeDetailsTaskList.scala.html
Accessibility Issue 'Information about you scheme' link aria attribute
> PODS-2836: Accessibility Issue 'Information about you scheme' link aria attribute

- app/forms/mappings/Constraints.scala
- app/forms/register/PersonDetailsFormProvider.scala
- app/views/components/date.scala.html
- app/views/components/input_date.scala.html
- conf/messages.en
- test/forms/mappings/ConstraintsSpec.scala
- test/forms/register/PersonDetailsFormProviderSpec.scala
PODS-2770: Pension scheme date fields (all) - You cannot get into all date fields
> PODS-2770: Pension scheme date fields (all) - You cannot get into all date fields

- app/views/benefitsSecuredByInsurance.scala.html
- app/views/investmentRegulatedScheme.scala.html
- app/views/occupationalPensionScheme.scala.html
- app/views/typeOfBenefits.scala.html
- conf/messages.en
- test/views/BenefitsSecuredByInsuranceViewSpec.scala
- test/views/InvestmentRegulatedSchemeViewSpec.scala
- test/views/OccupationalPensionSchemeViewSpec.scala
- test/views/TypeOfBenefitsViewSpec.scala
- test/views/behaviours/ViewBehaviours.scala
Created PR on behalf of Ashwani
> PODS-2743: pension scheme dynamic H1's

- app/assets/stylesheets/pensionsschemefrontend-app.scss
> PODS-2885: remove line under a establishers link

- conf/application.conf
Make sure the service doesn't attempt to render welsh messages
> Turn off welsh support

- app/views/components/input_text.scala.html
- app/views/components/input_yes_no.scala.html
- app/views/uKBankAccount.scala.html
- test/views/UKBankAccountViewSpec.scala
- test/views/behaviours/QuestionViewBehaviours.scala
- test/views/behaviours/YesNoViewBehaviours.scala
Reverts hmrc/pensions-scheme-frontend#980
> Revert "Pods 3480"

- app/utils/datacompletion/DataCompletionEstablishers.scala
- app/utils/hstasklisthelper/SpokeCreationService.scala
- app/views/register/addPartners.scala.html
- app/views/register/establishers/partnership/partner/whatYouWillNeed.scala.html
- conf/messages.en
- test/helpers/DataCompletionHelper.scala
- test/resources/payload.json
- test/utils/UserAnswersSpec.scala
Make sure all 3 of the Performance, Journey and Stubs are merged at the same time!
> PODS-4030 Minimum 2 partners mandatory

- project/AppDependencies.scala
Not all libraries upgraded as some we couldn't find in the repository
> Upgraded libraries

- app/services/UrlsPartialService.scala
…rtial. This is so that if back end endpoints removed in future an exception will be thrown and error detected during testing.
> PODS-5741 Scheme reg | Investigate how how scheme / racDac TTL operates

- README.md
> Fixed piping

- app/views/pspTaskList.scala.html
also view tidied, tab indening sorted and unused code and imports removed.
> psp view updated

- project/AppDependencies.scala
> PODS-7989: versions updated

- app/config/FrontendAppConfig.scala
- app/controllers/actions/AuthAction.scala
- conf/application.conf
- test/controllers/actions/AuthActionSpec.scala
This reverts commit 6641fc0c6c40126f021bcab4bf6e4ae0535c3f3f.
> Revert "PODS-9192: Introduced CL250 requirement"
